### ISSUE TITLE
Fix xdebug in MCD

### ISSUE THREAD

**Issue by ghost** [magento/magento-cloud-docker#342] opened 2022-03-21 13:36 UTC
### Preconditions
1. Magento 2.4.3
1. PHPStorm
1. Magento cloud docker installed
1. Magento Cloud docker image versions 1.3.0 or 1.3.1

### Steps to reproduce
1. Change all docker image versions in docker-compose.yml to 1.3.0 or 1.3.1
1. docker-compose down && docker-compose up -d
3.[ Follow these Adobe Commerce Cloud instructions to setup xdebug on PHP storm ](https://devdocs.magento.com/cloud/docker/docker-development-debug.html)
1. In PHPStorm add breakpoint to pub/index.php
1. Click start listening
1. Turn debugger on in browser
1. Refresh page or go to different pages
1. Debugger in phpstorm doesn't stop at breakpoint

### Expected result
1. When a page is loaded xdebug should stop at pub/index.php

### Actual result
1. When a page is loaded xdebug activate breakpoint at pub/index.php

**Comment by BaDos** [comment] 2022-04-11 19:11
Created the internal ticket MCLOUD-8642

**Comment by MagicLegend** [comment] 2022-04-12 14:28
I fiddled around with the xdebug config inside the xdebug container; and it seems like it's not adding `host.docker.internal` as the `client_host`; and instead falls back to `localhost:9001`. Manually adding the config in the container fixed the issue temporarily for me. Obviously after a container restart it'll be gone; so a permanent fix would be nice. But for now we can continue debugging by executing:

On your host:
```
docker exec -it <NAME>-docker_fpm_xdebug_1 /bin/bash
```

Then inside the container:
```
apt update
apt install nano
nano /usr/local/etc/php/conf.d/zz-xdebug-settings.ini
```

To which you have to append:
```
xdebug.client_host = host.docker.internal
```

Then finally you can restart `php-fpm` without restarting the container by running `kill -USR2 1` inside the container. You can verify `php-fpm` restarted with `ps aux`. 

If you want more context, you can enable xdebug logging in the same file:

```
xdebug.log = /app/var/log/xdebug-internal.log
```

**Comment by BaDos** [comment] 2022-04-13 21:03
I have created a PR to update the documentation.
There are only small changes regarding `client_host` and `client_port`

I have checked MCD 1.3.2 on MacOS and debugging works fine.

@AsrinDayananda288Group please try to use latest MCD 1.3.2 and generate the new `docker-compose.yaml`
All PHP images have xDebug 3 since MCD 1.3.1

**Comment by BaDos** [comment] 2022-04-13 21:08
@MagicLegend please check $XDEBUG_CONFIG inside your deploy container.
It should have this value `client_host=host.docker.internal`

Also, if you need to configure something you can do it in `docker-compose.yaml`, you do not need to change something inside a container.

**Comment by MagicLegend** [comment] 2022-04-14 06:58
@BaDos I can confirm it was set to that value. I can also confirm that xdebug was not using it, and instead tried to connect to `localhost:9001`. I'm also aware it can be set externally, but that seemed like a lot of effort for the day or two until this was fixed :)

I'll update my images to `1.3.2` and try again. Also my current `1.3.0` images also already have xDebug v3 (`3.0.4` to be exact).

**Comment by MagicLegend** [comment] 2022-04-14 07:39
Oh and @BaDos; is it intentional that the last two releases here did not have the `init-docker.sh` script as release artifact? Because it breaks the docs :)

**Comment by MagicLegend** [comment] 2022-04-14 09:25
And before I flush my logs again; this is what xdebug was reporting before in the `1.3.0` container:

```
[449] Log opened at 2022-04-12 14:10:08.163205
[449] [Step Debug] INFO: Connecting to configured address/port: localhost:9001.
[449] [Step Debug] WARN: Creating socket for 'localhost:9001', poll success, but error: Operation now in progress (29).
[449] [Step Debug] WARN: Creating socket for 'localhost:9001', connect: Cannot assign requested address.
[449] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9001 (through xdebug.client_host/xdebug.client_port) :-(
```

I can confirm that in the `1.3.2` container it now works correctly:

```
[113] Log opened at 2022-04-14 07:54:10.830127
[113] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9001.
[113] [Step Debug] WARN: Creating socket for 'host.docker.internal:9001', getaddrinfo: Invalid argument.
[113] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9001 (through xdebug.client_host/xdebug.client_port) :-(
[113] Log closed at 2022-04-14 07:54:10.975421
```

**Comment by BaDos** [comment] 2022-04-14 15:08
@MagicLegend thank you for the information regarding `init-docker.sh`, I will check it.

@AsrinDayananda288Group @MagicLegend I'm going to close this issue if 1.3.2 works correctly now. Please confirm.

**Comment by BaDos** [comment] 2022-04-18 19:04
The issue was closed because it was fixed in the latest MCD release.

**Closed as completed by BaDos** 2022-04-18 19:04 UTC
Labels: Progress: done
